# Generated by Django 4.1.5 on 2023-01-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_person_options_remove_person_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(auto_created=True, null=True),
        ),
    ]
