# Generated by Django 4.1.5 on 2023-01-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_first_name_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
