# Generated by Django 4.1.5 on 2023-01-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[(0, 'Не зарегистрирован'), (1, 'Зарегистрирован')], default='Не зарегистрирован', max_length=20),
        ),
    ]
