# Generated by Django 4.1.5 on 2023-01-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не зарегистрирован'), (1, 'Зарегистрирован')], default=0),
        ),
    ]
