# Generated by Django 4.1.5 on 2023-01-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_post_person_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
